"""empty message

Revision ID: 1da0a7c8bfcd
Revises: d2f33faed566
Create Date: 2023-03-11 20:20:40.553351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da0a7c8bfcd'
down_revision = 'd2f33faed566'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_game_id_user_id', 'player', ['game_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_id_user_id', table_name='player')
    # ### end Alembic commands ###
