"""empty message

Revision ID: 3daed1f04bf7
Revises: 3224d502a580
Create Date: 2023-03-08 11:25:39.895221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3daed1f04bf7'
down_revision = '3224d502a580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_state', 'current_player_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_state', 'current_player_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
