"""empty message

Revision ID: ba0e6b7c7ea0
Revises: 5e15e7601aa7
Create Date: 2023-03-08 15:36:43.804752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0e6b7c7ea0'
down_revision = '5e15e7601aa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_over', sa.Boolean(), nullable=True))
    op.create_index('idx_game_chat_id_is_over', 'game', ['chat_id', 'is_over'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_chat_id_is_over', table_name='game')
    op.drop_column('game', 'is_over')
    # ### end Alembic commands ###
